### ISSUE TITLE
SelectionMode is handled incorrect

### ISSUE THREAD

**Issue by bisato** [DavidWDev/DW.WPFToolkit#2]
Hello David,

according to [this](https://msdn.microsoft.com/en-US/library/system.windows.controls.selectionmode(v=vs.110).aspx) definition of SelectionMode, is Multiple Mode to be handled without modifier keys.
I propose you this code:
`else if (((Keyboard.Modifiers & ModifierKeys.Control) == ModifierKeys.Control) || SelectionMode == SelectionMode.Multiple)`
in Line 152 of EnhancedTreeView.cs.
With this Modification Items can be added/removed without pressing Modifiers, but only in SelectionMode "Multiple"

Greetings

Tobias

**Comment by DavidWDev** [comment]
Your solution looks nice, thanks.

No worry I don't forgot this report, I just had no time so far ^^

**Comment by DavidWDev** [comment]
Its fixed in the check-in 8fe714c436ba6ff30cb722265089c85f359ea31b
The version is published in the beta for the next release.
Download and docu: http://www.my-libraries.com/index.php/9-main-pages/24-dw-wpftoolkit-downloads
NuGet to the beta: https://www.nuget.org/packages/DW.WPFToolkit.Beta
